In [ ]:
import pandas as pd

pq = pd.read_parquet("")

In [38]:
pq

,messages,system_prompt,metadata,type
0,[{'content': 'Please write a succinct answer t...,,"{'abstract': 'In this paper, we introduce UniS...",None
1,[{'content': 'Please write a succinct answer t...,,"{'abstract': 'In this paper, we introduce UniS...",None
2,[{'content': 'Please write a succinct answer t...,,{'abstract': 'The rise of social media is enab...,None
3,[{'content': 'Please write a succinct answer t...,,{'abstract': 'The rise of social media is enab...,None
4,[{'content': 'Please write a succinct answer t...,,{'abstract': 'Sentiment Analysis of microblog ...,None
...,...,...,...,...
57,[{'content': 'Please write a succinct answer t...,,{'abstract': 'The Coronavirus pandemic has tak...,None
58,[{'content': 'Please write a succinct answer t...,,"{'abstract': 'Cryptocurrencies, such as Bitcoi...",None
59,[{'content': 'Please write a succinct answer t...,,"{'abstract': 'Cryptocurrencies, such as Bitcoi...",None
60,[{'content': 'Please write a succinct answer t...,,"{'abstract': 'Cryptocurrencies, such as Bitcoi...",None
61,[{'content': 'Please write a succinct answer t...,,"{'abstract': 'Cryptocurrencies, such as Bitcoi...",None

In [34]:
pq

,messages,system_prompt,metadata,type
0,[{'content': 'Please write a succinct answer t...,,"{'abstract': 'Bilingual lexicon induction, tra...",None
1,[{'content': 'Please write a succinct answer t...,,"{'abstract': 'Bilingual lexicon induction, tra...",None
2,[{'content': 'Please write a succinct answer t...,,"{'abstract': 'Bilingual lexicon induction, tra...",None
3,[{'content': 'Please write a succinct answer t...,,{'abstract': 'It has been shown that the perfo...,None
4,[{'content': 'Please write a succinct answer t...,,{'abstract': 'It has been shown that the perfo...,None
...,...,...,...,...
64,[{'content': 'Please write a succinct answer t...,,{'abstract': 'We study methods for learning se...,None
65,[{'content': 'Please write a succinct answer t...,,{'abstract': 'Sequence-to-sequence (seq2seq) a...,None
66,[{'content': 'Please write a succinct answer t...,,{'abstract': 'Sequence-to-sequence (seq2seq) a...,None
67,[{'content': 'Please write a succinct answer t...,,{'abstract': 'Sequence-to-sequence (seq2seq) a...,None
68,[{'content': 'Please write a succinct answer t...,,{'abstract': 'Sequence-to-sequence (seq2seq) a...,None

In [33]:
from datasets import load_dataset

ds = load_dataset("qtris123/qtris123qasper-rewrite-gpt-4.1-SA-task")

In [32]:
ds["question"].to_pandas()

,paper_id,title,abstract,question,answer,old_answer,old_question
0,1904.09678,UniSent: Universal Adaptable Sentiment Lexica ...,"In this paper, we introduce UniSent a universa...","In the paper ""UniSent: Universal Adaptable Sen...",Accuracy and macro-F1 (averaged F1 over positi...,{'evidence': ['FLOAT SELECTED: Table 1: Compar...,how is quality measured?
1,1904.09678,UniSent: Universal Adaptable Sentiment Lexica ...,"In this paper, we introduce UniSent a universa...",Which sentiment lexica or resources do the aut...,"Manually created sentiment lexica in Czech, Ge...",{'evidence': ['As the gold standard sentiment ...,what sentiment sources do they compare with?
2,1808.05077,Exploiting Deep Learning for Persian Sentiment...,The rise of social media is enabling people to...,"According to the paper ""Exploiting Deep Learni...",CNN achieved the highest performance in sentim...,{'evidence': ['To evaluate the performance of ...,Which deep learning model performed better?
3,1808.05077,Exploiting Deep Learning for Persian Sentiment...,The rise of social media is enabling people to...,"According to the paper ""Exploiting Deep Learni...",Accuracy of 82.6%.,{'evidence': ['To evaluate the performance of ...,What was their performance on the dataset?
4,1912.05066,Event Outcome Prediction using Sentiment Analy...,Sentiment Analysis of microblog feeds has attr...,"In the paper ""Event Outcome Prediction using S...",Two labels: sentiment polarity and candidate/c...,"{'evidence': ['For the sentiment analysis, we ...",How many label options are there in the multi-...
...,...,...,...,...,...,...,...
57,2004.03925,Word frequency and sentiment analysis of twitt...,The Coronavirus pandemic has taken the world b...,"In the paper ""Word frequency and sentiment ana...",No; the authors collect Twitter data in Englis...,"{'evidence': ['In this section, we present the...",Do they collect only English data?
58,2003.04967,KryptoOracle: A Real-Time Cryptocurrency Price...,"Cryptocurrencies, such as Bitcoin, are becomin...","In the paper ""KryptoOracle: A Real-Time Crypto...",Yes. All non-English tweets were filtered out ...,{'evidence': ['Twitter data: We used the Twitt...,Do they evaluate only on English datasets?
59,2003.04967,KryptoOracle: A Real-Time Cryptocurrency Price...,"Cryptocurrencies, such as Bitcoin, are becomin...",What experimental evaluation is used in the pa...,Root mean square error between actual and pred...,{'evidence': ['Once the KryptoOracle engine wa...,What experimental evaluation is used?
60,2003.04967,KryptoOracle: A Real-Time Cryptocurrency Price...,"Cryptocurrencies, such as Bitcoin, are becomin...","According to the paper ""KryptoOracle: A Real-T...",By leveraging Apache Spark’s resilient distrib...,{'evidence': ['KryptoOracle has been built in ...,How is the architecture fault-tolerant?
61,2003.04967,KryptoOracle: A Real-Time Cryptocurrency Price...,"Cryptocurrencies, such as Bitcoin, are becomin...","In the paper ""KryptoOracle: A Real-Time Crypto...","handling large volume incoming data, sentiment...",{'evidence': ['In this paper we provide a nove...,Which elements of the platform are modular?